name: build-v3s

on:
  workflow_dispatch:
    inputs:
      git-address:
        description: 'git-address'
        required: true
        default: 'https://github.com/buildroot/buildroot.git'
      branches-tags:
        description: 'branches-tags'
        required: true
        default: '2018.08.2'
      board:
        description: 'board'
        required: true
        default: 'v3s'
      custom-board:
        description: 'custom-board'
        required: false
        default: 'v3s'
      build-with:
        description: 'build-with'
        required: false
        default: ''


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Clone source code
      run: |
        git clone ${{github.event.inputs.git-address}} /opt/buildroot
        cd /opt/buildroot

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install -y make gcc g++ unzip git bc python device-tree-compiler mtd-utils
        sudo apt install gcc build-essential bison flex gettext tcl sharutils libncurses-dev zlib1g-dev exuberant-ctags g++ texinfo patch vim libtool bc git python3 unzip python3-distutils swig python-dev tree
        sudo apt install gcc-arm-linux-gnueabihf

    - name: Bulid
      run: |
        mkdir /opt/firmware
        cd /opt/buildroot
        git checkout ${{github.event.inputs.branches-tags}}
        git pull origin ${{github.event.inputs.branches-tags}}
        echo '---start copy files---'
        cp -r /home/runner/work/buildroot-actions/buildroot-actions/${{github.event.inputs.custom-board}}/buildroot /opt
        tree output/
        echo '---start make---'
        make
        echo '---start pack---'
        sudo sh ./pack.sh
        echo '---start copy firmware---'
        cp flash_32m.bin /opt/firmware
        cp files.tgz /opt/firmware
        cp flash.tgz /opt/firmware
        echo '---END---'

    - name : Upload buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
      uses: actions/upload-artifact@master
      with:
        name: buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
        path: /opt/firmware
