name: build-v3s

on:
  workflow_dispatch:
    inputs:
      git-address:
        description: 'git-address'
        required: true
        default: 'https://github.com/buildroot/buildroot.git'
      branches-tags:
        description: 'branches-tags'
        required: true
        default: '2018.08.2'
      board:
        description: 'board'
        required: true
        default: 'v3s'
      build-with:
        description: 'build-with'
        required: false
        default: ''


jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Clone source code
      run: |
        git clone ${{github.event.inputs.git-address}} /opt/buildroot
        cd /opt/buildroot

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install -y make gcc g++ unzip git bc python device-tree-compiler mtd-utils

    - name: Bulid
      run: |
        mkdir /opt/firmware
        cd /opt/buildroot
        git checkout ${{github.event.inputs.branches-tags}}
        git pull origin ${{github.event.inputs.branches-tags}}
        echo '---start copy files---'
        cp -ra /home/runner/work/buildroot-actions/buildroot-actions/${{github.event.inputs.board}}/buildroot /opt
        echo '---start make---'
        make
        echo '---pre_build---'
        cp -rf /home/runner/work/buildroot-actions/buildroot-actions/${{github.event.inputs.board}}/buildroot /opt
        cd /opt/buildroot
        sh ./pre_build.sh
        make
        echo '---start pack---'
        sh ./pack.sh
        echo '---start copy firmware---'
        cp output/build/uboot-v3s-spi-experimental/u-boot-sunxi-with-spl.bin /opt/firmware
        cp output/images/sun8i-v3s-licheepi-zero-dock.dtb /opt/firmware
        cp output/images/zImage /opt/firmware
        cp jffs2.bin /opt/firmware
        cp flash_32m.bin /opt/firmware
        echo '---END---'

    - name : Upload buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
      uses: actions/upload-artifact@master
      with:
        name: buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
        path: /opt/firmware
